# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_make_time',
            field=models.CharField(default='1 hour', max_length=50),
            preserve_default=False,
        ),
    ]
