# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('courses', '0002_auto_20170317_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login_reg.User'),
            preserve_default=False,
        ),
    ]
