# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_id',
            new_name='student',
        ),
    ]
