# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170321_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_of_students',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
