# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170324_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
