# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_favorite_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_count',
            new_name='quote_count',
        ),
    ]
