-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 13:22:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emails_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emails_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emails_db` DEFAULT CHARACTER SET utf8 ;
USE `emails_db` ;

-- -----------------------------------------------------
-- Table `emails_db`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emailsdb`.`emails` (
  `id` INT NOT NULL auto_increment,
  `email_address` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
